### ISSUE TITLE
Add ts declaration file for the package, So that developers can conveniently use it with typescript.

### ISSUE THREAD

**Issue by redeyes420420** [binarykitchen/find-remove#22]

**Comment by redeyes420420** [comment]
Now, it can be solved with // @ts-ignore before the import line.

**Comment by binarykitchen** [comment]
alright, i've just added that line and published that within v2.0.1

but in theory even that @ts-ignore line can be suppressed with https://palantir.github.io/tslint/rules/ban-ts-ignore/
