### ISSUE TITLE
TypeError: findRemoveSync is not a function

### ISSUE THREAD

**Issue by sadashivm** [binarykitchen/find-remove#26]
Hello, I'm getting the below error and I'm using this npm package with Electron JS and react js application.

![image](https://user-images.githubusercontent.com/10355473/106792146-cb22d400-667b-11eb-8804-ff98dabed88e.png)

And here is my code,
![image](https://user-images.githubusercontent.com/10355473/106792268-ed1c5680-667b-11eb-8ccf-734a7732860b.png)

**Comment by binarykitchen** [comment]
Mate, mixing `require` and `import` in the same file is no good idea.

Try importing findRemoveSync instead of requiring.
