### ISSUE TITLE
Node 18 support

### ISSUE THREAD

**Issue by dell-mic** [binarykitchen/find-remove#35]
Hi,

thanks a lot for this package.

While upgrading some projects to node 18 (will be the next LTS version) I noticed that this package claims to not be compatible:
```
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'find-remove@4.0.4',
npm WARN EBADENGINE   required: { node: '^16.13.1', npm: '^8.1.2' },
npm WARN EBADENGINE   current: { node: 'v18.9.1', npm: '8.19.2' }
npm WARN EBADENGINE }
```

Nevertheless in my project by installing with --ignore-engines seems to work well.

Best,
Michael

**Comment by binarykitchen** [comment]
Right, just fixed that. Thanks for raising.
